const countries = [
  { label: "United States of America", value: "US" },
  { label: "United Kingdom", value: "GB" },
  { label: "India", value: "IN" },
  { label: "France", value: "FR" },
  { label: "Japan", value: "JP" },
  { label: "South Korea", value: "KR" },
  { label: "Germany", value: "DE" },
  { label: "Italy", value: "IT" },
  { label: "Spain", value: "ES" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "China", value: "CN" },
  { label: "Brazil", value: "BR" },
  { label: "Russia", value: "RU" },
  { label: "Sweden", value: "SE" },
  { label: "Mexico", value: "MX" },
  { label: "Argentina", value: "AR" },
  { label: "Turkey", value: "TR" },
  { label: "Netherlands", value: "NL" },
  { label: "Denmark", value: "DK" },
  { label: "Norway", value: "NO" },
  { label: "Belgium", value: "BE" },
  { label: "Hong Kong", value: "HK" },
  { label: "Ireland", value: "IE" },
  { label: "Austria", value: "AT" },
  { label: "Switzerland", value: "CH" },
  { label: "Poland", value: "PL" },
  { label: "Finland", value: "FI" },
  { label: "New Zealand", value: "NZ" },
  { label: "Portugal", value: "PT" },
  { label: "South Africa", value: "ZA" },
  { label: "Czech Republic", value: "CZ" },
  { label: "Hungary", value: "HU" },
  { label: "Israel", value: "IL" },
  { label: "Greece", value: "GR" },
  { label: "Indonesia", value: "ID" },
  { label: "Thailand", value: "TH" },
  { label: "Philippines", value: "PH" },
  { label: "Taiwan", value: "TW" },
  { label: "Malaysia", value: "MY" },
  { label: "Singapore", value: "SG" },
  { label: "Vietnam", value: "VN" },
  { label: "Colombia", value: "CO" },
  { label: "Chile", value: "CL" },
  { label: "Egypt", value: "EG" },
  { label: "Nigeria", value: "NG" },
  { label: "Pakistan", value: "PK" },
  { label: "Romania", value: "RO" },
  { label: "Iceland", value: "IS" },
  { label: "Peru", value: "PE" },
];

export default countries;